# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6acd25526932cb9e1b886cf1f29015b2"
name = "pet-profile-development"
handle = "pet-profile-development"
application_url = "https://conferences-nam-doing-letting.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_write_customers,read_customers,write_customers"

[auth]
redirect_urls = ["https://conferences-nam-doing-letting.trycloudflare.com/auth/callback", "https://conferences-nam-doing-letting.trycloudflare.com/auth/shopify/callback", "https://conferences-nam-doing-letting.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://conferences-nam-doing-letting.trycloudflare.com/app-proxy/pet-profile-development"
subpath = "pet-profile-development"
prefix = "apps"

[pos]
embedded = false

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
